-   repo: https://github.com/Yelp/detect-secrets.git
  #git@github.com:Yelp/detect-secrets
    rev: v0.13.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        #        exclude: .*/tests/.*
