version: 2.1 # use CircleCI 2.1
orbs:
  browser-tools: circleci/browser-tools@2.3.2
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/faidare # directory where steps will run

    docker: # run the steps with Docker
      - image: cimg/openjdk:21.0.9-browsers # ...with this image as the primary container; this is where all `steps` will run
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.17.29
        name: elasticsearch
        environment:
          transport.host: localhost
          network.host: elasticsearch
          http.port: 9200
          cluster.name: es-cluster
          discovery.type: single-node
          xpack.security.enabled: false
          ES_JAVA_OPTS: -Xms750m -Xmx750m

    steps: # a collection of executable commands
      - browser-tools/install_chrome
      # check out source code to working directory
      - checkout
      # wait for elasticsearch to start and be ready
      # (this takes a few seconds and is necessary)
      - run: until curl -s "http://elasticsearch:9200/_cluster/health?wait_for_status=green&timeout=60s"; do sleep 1; done
      # load the test data
      - run: ./scripts/harvest.sh -jsonDir "./data/test/" -es_host "elasticsearch" -es_port "9200" -env "dev" -type "all" --verbose </dev/null
      - run: ./gradlew check build
